name: Convert PUML to SVG
on: push
jobs:
  convert_puml_to_svg:
    runs-on: ubuntu-latest
    steps:
      # 必要な依存関係のインストール
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          sudo apt-get install plantuml

      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4


      # .pumlファイルを処理してSVGに変換
      - name: Process Diagrams
        run: |
          cd puml
          for file in $(find . -name "*.puml"); do
            java -jar plantuml-1.2024.5.jar -svg "$file" -charset UTF-8
          done

      # 生成されたSVGファイルの表示（デバッグ用）
      - name: Display SVG Files
        run: |
          find . -name "*.svg" | xargs ls -l

      - name: Commit and Push Diagrams
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: ':rocket: Add generated SVG diagrams'
          add: '.'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}