name: Convert PUML to SVG
on: push
jobs:
  convert_puml_to_svg:
    runs-on: ubuntu-latest
    steps:
      # 必要な依存関係のインストール
      - name: Install Dependencies
        run: |
         sudo apt-get install graphviz
         sudo apt-get install fonts-noto-cjk

      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4


      # .pumlファイルを処理してSVGに変換
      - name: Process Diagrams
        run: |
          ls -a
          export LANG = "ja_JP.UTF-8"
          set LANG="ja_JP.UTF-8"
          cd puml
          mkdir output
          for file in $(find . -name "*.puml"); do
            cat "$file" | docker run --rm -i think/plantuml > "${file%.puml}.svg"
            svg_file="${file%.puml}.svg"
            mv "$svg_file" ./output
          done

      # 生成されたSVGファイルの表示（デバッグ用）
      - name: Display SVG Files
        run: |
          find . -name "*.svg" | xargs ls -l


      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          # 保存ファイル名（name.zip）
          name: output
          # 保存するファイル
          path: puml/output

          # 保存期間（日）
          retention-days: 3