name: Convert PUML to SVG
on: push
jobs:
  convert_puml_to_svg:
    runs-on: ubuntu-latest
    steps:
      # 必要な依存関係のインストール
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          sudo apt-get install plantuml

      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4


      # .pumlファイルを処理してSVGに変換
      - name: Process Diagrams
        run: |
          cd puml
          for file in $(find . -name "*.puml"); do
            java -jar plantuml-1.2024.5.jar -svg "$file" -charset UTF-8
          done

      # 生成されたSVGファイルの表示（デバッグ用）
      - name: Display SVG Files
        run: |
          find . -name "*.svg" | xargs ls -l

      # 変更されたファイルをコミット
      - name: Commit Diagrams
        run: |
          cd puml_GA
          git config --local user.email "daichi_kiyozaki@nuco.co.jp"
          git config --local user.name "daichi-kiyozaki"
          git add .
          git commit -m ":rocket: Add generated SVG diagrams" || exit 0

      # 変更をプッシュ
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
