name: Convert PUML to SVG
on: push
jobs:
  convert_puml_to_svg:
    runs-on: ubuntu-latest
    steps:
      # 必要な依存関係のインストール
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          sudo apt-get install plantuml

      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4


      # .pumlファイルを処理してSVGに変換
      - name: Process Diagrams
        run: |
          ls -a
          cd puml
          for file in $(find . -name "*.puml"); do
            java -jar plantuml-1.2024.5.jar -svg "$file" -charset UTF-8
          done

      # 生成されたSVGファイルの表示（デバッグ用）
      - name: Display SVG Files
        run: |
          find . -name "*.svg" | xargs ls -l


      - name: push diff
        run: |
          pwd
          git init
          git remote set-url origin https://github.com/daichi-kiyozaki/puml_GA.git
          git config --global user.email "daichi_kiyozaki@nuco.co.jp"
          git config --global user.name "daichi-kiyozaki"
          git add .
          git status
          git commit -m "GitHub Actions から差分を Push"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}